MetalDetector = MetalDetector or {}

local GM = GM or GAMEMODE
GM.Config = GM.Config or {}
GM.Config.PocketBlacklist = GM.Config.PocketBlacklist or {}

GM.Config.PocketBlacklist["metal_detector"] = true

DarkRP.createEntity("Metal Detector", {
	ent = "metal_detector",
	model = "models/props_wasteland/interior_fence002e.mdl",
	price = 1500,
	max = 1,
	cmd = "buymetaldetector"
})

MetalDetector.WhiteListEnabled = true

-- A modifier for the distance this sound will reach, acceptable range is 0 to 511. 100 means no adjustment to the level.
MetalDetector.BuzzSoundLevel = 100
-- The pitch applied to the sound. The acceptable range is from 0 to 255. 100 means the pitch is not changed.
MetalDetector.BuzzPitchPercent = 100

-- A modifier for the distance this sound will reach, acceptable range is 0 to 511. 100 means no adjustment to the level.
MetalDetector.DingSoundLevel = 100
-- The pitch applied to the sound. The acceptable range is from 0 to 255. 100 means the pitch is not changed.
MetalDetector.DingPitchPercent = 100

MetalDetector.GUIFadeDistance = 3000

MetalDetector.GovTeams = {
	["Police Officer"] = true,
    ["Mechanical Officer"] = true,
	["Mayor"] = true,
	["Chief of Police"] = true,
	["S.W.A.T Sniper"] = true,
	["S.W.A.T"] = true,
	["S.W.A.T Team Leader"] = true,
	["S.W.A.T Medic"] = true,
	["S.W.A.T Juggernaut"] = true,
	["Mayors Bodyguard"] = true,
	["Mayors Daughter"] = true,
	["Mayors Wife"] = true,
	["Mayors Secretary"] = true,
	["CGSF Commander"] = true,
	["CGSF Captain"] = true,
	["CGSF Sergeant"] = true,
	["CGSF Corporal"] = true,
	["CGSF Specialist"] = true,
	["CGSF Private"] = true,
}

MetalDetector.WhiteList = {
	["weapon_physgun"]       = true,
	["weapon_physcannon"]    = true,
	["weapon_droneradar"] 	 = true,
	["weapon_remotedrone"]   = true,
	["weapon_dronerepair"]   = true,
	["gmod_tool"]            = true,
	["gmod_camera"]          = true,
	["pocket"]               = true,
	["keys"]                 = true,
	["stunstick"]            = true,
	["vc_repair"]	 		 = true,
	["weapon_arc_atmhack"]   = true,
	["weapon_checker"]  	 = true,
	["arrest_stick"]         = true,
	["unarrest_stick"]       = true,
	["weaponchecker"]        = true,
	["door_ram"]             = true,
	["weapon_profiler"]		 = true,
	["climb_swep2"]			 = true,
	["laserpointer"]		 = true,
	["weapon_medkit"]		 = true,
	["weapon_arc_atmcard"] 	 = true,
	["weapon_keypadchecker"] = true,
	["itemstore_pickup"]	 = true,
	["lockpick"]			 = true,
	["steel_lockpick"]		 = true,
	["rigged_keypad_cracker"]= true,
	["keypad_cracker"]       = true,
	["weapon_hack_phone"]    = true,
	["weapon_fists"]         = true,
	["weapon_shovel"]        = true,
	["med_kit"]				 = true,
	["weapon_hacking_keycard"]	= true,
	["weapon_keycard"]		 = true,
	["weapon_boombox"]       = true,
	["disguise2"]      		 = true,
	["parkourmod"]			 = true,
	["snowball_thrower_nodamage"] = true,
	["hydro_ephone_swep"] 	 = true,
	["duckgun"] 			 = true,
	["weapon_popcorn"] 		 = true,
	["weapon_popcorn_spam"]  = true,
	["wowozela"] 			 = true,
	["weapon_spraymhs"] 	 = true,
	["weapon_maxnet_delivery_marker"] = true,
	["weapon_sh_keypadcracker_deploy"] = true,
	
	// Knives
	["csgo_gut_damascus"] = true,
	["csgo_flip_boreal"] = true,
	["csgo_butterfly_rustcoat"] = true,
	["csgo_gut"] = true,
	["csgo_huntsman_bluesteel"] = true,
	["csgo_falchion_tiger"] = true,
	["csgo_gut_case"] = true,
	["csgo_bayonet_ultraviolet"] = true,
	["csgo_m9_marblefade"] = true,
	["csgo_karambit"] = true,
	["csgo_butterfly_ddpat"] = true,
	["csgo_falchion_fade"] = true,
	["csgo_gut_night"] = true,
	["csgo_butterfly_night"] = true,
	["csgo_flip_crimsonwebs"] = true,
	["csgo_bayonet_fade"] = true,
	["csgo_bayonet_ddpat"] = true,
	["csgo_huntsman_case"] = true,
	["csgo_daggers_damascus"] = true,
	["csgo_huntsman_damascus"] = true,
	["csgo_butterfly"] = true,
	["csgo_m9_ultraviolet"] = true,
	["csgo_bayonet_crimsonwebs"] = true,
	["csgo_flip_damascus"] = true,
	["csgo_flip_case"] = true,
	["csgo_bowie_ultraviolet"] = true,
	["csgo_bayonet_slaughter"] = true,
	["csgo_flip_fade"] = true,
	["csgo_karambit_night"] = true,
	["csgo_bowie_damascus"] = true,
	["csgo_falchion_marblefade"] = true,
	["csgo_falchion_bluesteel"] = true,
	["csgo_daggers_case"] = true,
	["csgo_bowie_night"] = true,
	["csgo_daggers_marblefade"] = true,
	["csgo_bowie_marblefade"] = true,
	["csgo_bowie_crimsonwebs"] = true,
	["csgo_huntsman_rustcoat"] = true,
	["csgo_m9"] = true,
	["csgo_bayonet_bluesteel"] = true,
	["csgo_m9_crimsonwebs"] = true,
	["csgo_falchion_case"] = true,
	["csgo_falchion_night"] = true,
	["csgo_butterfly_fade"] = true,
	["csgo_bayonet_night"] = true,
	["csgo_daggers_ultraviolet"] = true,
	["csgo_bayonet_damascus"] = true,
	["csgo_bowie_case"] = true,
	["csgo_bayonet_marblefade"] = true,
	["csgo_default_golden"] = true,
	["csgo_gut_tiger"] = true,
	["csgo_huntsman_marblefade"] = true,
	["csgo_bayonet_tiger"] = true,
	["csgo_karambit_crimsonwebs"] = true,
	["csgo_karambit_ddpat"] = true,
	["csgo_m9_rustcoat"] = true,
	["csgo_daggers_boreal"] = true,
	["csgo_bowie_slaughter"] = true,
	["csgo_bayonet_rustcoat"] = true,
	["csgo_gut_rustcoat"] = true,
	["csgo_butterfly_damascus"] = true,
	["csgo_gut_marblefade"] = true,
	["csgo_daggers_greyscaled"] = true,
	["csgo_daggers_fade"] = true,
	["csgo_flip_tiger"] = true,
	["csgo_huntsman_slaughter"] = true,
	["csgo_butterfly_tiger"] = true,
	["csgo_bowie_tiger"] = true,
	["csgo_m9_slaughter"] = true,
	["csgo_gut_boreal"] = true,
	["csgo_cssource"] = true,
	["csgo_falchion_slaughter"] = true,
	["csgo_default_knife"] = true,
	["csgo_gut_slaughter"] = true,
	["csgo_flip_night"] = true,
	["csgo_daggers_night"] = true,
	["csgo_falchion_crimsonwebs"] = true,
	["csgo_falchion_boreal"] = true,
	["csgo_default_t"] = true,
	["csgo_butterfly_boreal"] = true,
	["csgo_falchion_ultraviolet"] = true,
	["csgo_gut_bluesteel"] = true,
	["csgo_m9_bluesteel"] = true,
	["csgo_huntsman_fade"] = true,
	["csgo_m9_tiger"] = true,
	["csgo_default_t_golden"] = true,
	["csgo_flip_ultraviolet"] = true,
	["csgo_karambit_damascus"] = true,
	["csgo_flip_slaughter"] = true,
	["csgo_bayonet_case"] = true,
	["csgo_gut_crimsonwebs"] = true,
	["csgo_bowie_bluesteel"] = true,
	["csgo_karambit_case"] = true,
	["csgo_huntsman_boreal"] = true,
	["csgo_karambit_slaughter"] = true,
	["csgo_bowie"] = true,
	["csgo_daggers_slaughter"] = true,
	["csgo_bowie_boreal"] = true,
	["csgo_karambit_rustcoat"] = true,
	["csgo_falchion_rustcoat"] = true,
	["csgo_flip_rustcoat"] = true,
	["csgo_butterfly_crimsonwebs"] = true,
	["csgo_gut_fade"] = true,
	["csgo_huntsman_crimsonwebs"] = true,
	["csgo_butterfly_slaughter"] = true,
	["csgo_falchion_damascus"] = true,
	["csgo_daggers_tiger"] = true,
	["csgo_daggers_ddpat"] = true,
	["csgo_flip_ddpat"] = true,
	["csgo_falchion_ddpat"] = true,
	["csgo_flip"] = true,
	["csgo_m9_damascus"] = true,
	["csgo_karambit_marblefade"] = true,
	["csgo_m9_fade"] = true,
	["csgo_karambit_boreal"] = true,
	["csgo_huntsman_tiger"] = true,
	["csgo_huntsman_ddpat"] = true,
	["csgo_daggers_rustcoat"] = true,
	["csgo_bowie_rustcoat"] = true,
	["csgo_flip_marblefade"] = true,
	["csgo_huntsman"] = true,
	["csgo_gut_ddpat"] = true,
	["csgo_m9_case"] = true,
	["csgo_bayonet_boreal"] = true,
	["csgo_gut_ultraviolet"] = true,
	["csgo_karambit_fade"] = true,
	["csgo_daggers_webs"] = true,
	["csgo_huntsman_ultraviolet"] = true,
	["csgo_bowie_fade"] = true,
	["csgo_huntsman_night"] = true,
	["csgo_bowie_ddpat"] = true,
	["csgo_m9_ddpat"] = true,
	["csgo_butterfly_marblefade"] = true,
	["csgo_flip_bluesteel"] = true,
	["csgo_karambit_ultraviolet"] = true,
	["csgo_m9_night"] = true,
	["csgo_karambit_bluesteel"] = true,
	["csgo_bayonet"] = true,
	["csgo_butterfly_case"] = true,
	["csgo_butterfly_bluesteel"] = true,
	["csgo_m9_boreal"] = true,
	["csgo_daggers"] = true,
	["csgo_karambit_tiger"] = true,
	["csgo_daggers_bluesteel"] = true,
	["csgo_falchion"] = true,
	["csgo_butterfly_ultraviolet"] = true,
	
	// Custom knife skins
	["csgo_karambit_creamy"] = true,
	["csgo_karambit_sticker"] = true,
	["csgo_karambit_space"] = true,
	["csgo_karambit_modern"] = true,
	["csgo_karambit_lava"] = true,
	["csgo_karambit_doppler"] = true,
	["csgo_karambit_burning"] = true,
	["csgo_karambit_bluetiger"] = true,
	["csgo_karambit_rainbow"] = true,
	["csgo_karambit_aurora"] = true,
	["csgo_karambit_wankish"] = true,
	["csgo_karambit_theorem"] = true,
	["csgo_karambit_template"] = true,

	-- Ventz drinks
	["ventz_drink_blackvelvet"] = true,
	["ventz_drink_blood"] = true,
	["ventz_drink_brandy"] = true,
	["ventz_drink_cosmopolitan"] = true,
	["ventz_drink_cosmopolitan"] = true,
	["ventz_drink_margarita"] = true,
	["ventz_drink_martini"] = true,

}

MetalDetector.BlackList = {
	"weapon_ak472",
	"weapon_deagle2",
	"weapon_fiveseven2",
	"weapon_glock2",
	"weapon_m42",
	"weapon_mac102",
	"weapon_mp52",
	"weapon_p2282",
	"weapon_pumpshotgun2",
	"ls_sniper",
	"lockpick",
	--m9k
	"m9k_coltpython",
	"m9k_colt1911",
	"m9k_hk45",
	"m9k_luger",
	"m9k_ragingbull",
	"m9k_model500",
	"m9k_m29satan",
	"m9k_m92baretta",
	"m9k_model3russian",
	"m9k_model627",
	"m9k_acr",
	"m9k_amd65",
	"m9k_fal",
	"m9k_m14sp",
	"m9k_m16a4_acog",
	"m9k_m416",
	"m9k_scar",
	"m9k_tar21",
	"m9k_val",
	"m9k_vikhr",
	"m9k_winchester73",
	"m9k_1887winchester",
	"m9k_dbarrel",
	"m9k_jackhammer",
	"m9k_m3",
	"m9k_ithacam37",
	"m9k_mossberg590",
	"m9k_remington870",
	"m9k_1897winchester",
	"weapon_mad_xm1014",
	"m9k_barret_m82",
	"m9k_m98b",
	"m9k_svt40",
	"m9k_svu",
	"m9k_dragunov",
	"m9k_intervention",
	"m9k_psg1",
	"m9k_aw50",
	"m9k_m24",
	"m9k_remington7615p",
	"m9k_contender",
	"weapon_mad_awp",
	"weapon_mad_scout",
	"m9k_fg42",
	"m9k_m60",
	"weapon_m3684",
	"weapon_mad_m249",
	"m9k_minigun",
	--fas2
	"fas2_ammobox",
	"fas2_ak12",
	"fas2_ak47",
	"fas2_m24",
	"fas2_rpk",
	"fas2_ak74",
	"fas2_mp5a5",
	"fas2_g3",
	"fas2_glock20",
	"fas2_m3s90",
	"fas2_sg552",
	"fas2_rk95",
	"fas2_ragingbull",
	"fas2_pp19",
	"fas2_sks",
	"fas2_an94",
	"fas2_dv2",
	"fas2_galil",
	"fas2_deagle",
	"fas2_g36c",
	"fas2_famas",
	"fas2_uzi",
	"fas2_ifak",
	"fas2_ks23",
	"fas2_mac11",
	"fas2_m14",
	"fas2_m1911",
	"fas2_m79",
	"fas2_m67",
	"fas2_m4a1",
	"fas2_machete",
	"fas2_mp5k",
	"fas2_mp5sd6",
	"fas2_ots33",
	"fas2_rem870",
	"fas2_p226",
	"fas2_sg550",
	"fas2_sr25",
	"fas2_toz34"
}